# tiny config to check the code runs, finishes in seconds on a CPU
tokenizer: simple

# model parameters
model_type: bigram
vocab_size: 65

# data
data_path: data/tinyshakespeare.txt
max_seq_len: 1
train_split: 0.9 # proportion of dataset to use for training, rest is for validation

# training
batch_size: 8
iterations: 200

# optimization
optimizer: AdamW
lr: 1e-3
beta1: 0.9
beta2: 0.999
eps: 1e-8
weight_decay: 0.01

# evaluation
eval_iterations: 4
eval_interval: 50

# recorded in the results and used in the results file name
experiment: debug-bigram

# reproducibility
seed: 100
