tokenizer: simple

# model parameters
model_type: attention
vocab_size: 65

# data
data_path: data/tinyshakespeare.txt
block_size: 16
train_split: 0.9 # proportion of dataset to use for training, rest is for validation

# training
batch_size: 32
iterations: 2500

# optimization
optimizer: AdamW
lr: 1e-3

# evaluation
eval_iterations: 100
eval_interval: 500

# attention head parameters
n_embd: 128
num_heads: 4
dropout: 0.1
group_size: 2
