tokenizer: simple

# model parameters
model_type: bigram
vocab_size: 257

# data
data_path: data/tinyshakespeare.txt
max_seq_len: 1
train_split: 0.9 # proportion of dataset to use for training, rest is for validation

# training
batch_size: 32
iterations: 25000

# optimization
optimizer: AdamW
lr: 1e-3

# evaluation
eval_iterations: 100
eval_interval: 500

