tokenizer: bpe

# model parameters
model_type: transformer
vocab_size: 257

# data
data_path: data/tinyshakespeare.txt
max_seq_len: 16
train_split: 0.9 # proportion of dataset to use for training, rest is for validation

# training
batch_size: 32
iterations: 10000

# optimization
optimizer: AdamW
lr: 1e-3

# evaluation
eval_iterations: 100
eval_interval: 500

# attention head parameters
n_embd: 128
num_heads: 4
dropout: 0.1
group_size: 1

# transformer specific parameters
n_layers: 4